bind_port = 8095
bind_host = "0.0.0.0"
payload_size_limit = "2mb"

token_secret = "secret"

default_workspace_uuid = "11111111-2222-3333-4444-555555555555"

redis_urls = "redis://127.0.0.1:6379"
redis_password = "<invalid>"
redis_mode = "direct"
redis_service = "mymaster"
